### ISSUE TITLE
Compilation stop with  Class Magento\GiftWrapping\Api\WrappingRepositoryInterface does not exist  Error in Affirm 2 plugin

### ISSUE THREAD

**Issue by devishreebalasubramanian** [astoundcommerce/affirm2#1]
Hai,

  I have installed this plugin in magento 2 project.It works fine.But when i compile i got this error.
After delete this plugin this error doesn't come.

**[ReflectionException]  
Class Magento\GiftWrapping\Api\WrappingRepositoryInterface does not exist** 

please help me to resolve this issue.

**Comment by alexrandom** [comment]
Hi @devishreebalasubramanian,

this issue is reproducible on Community Edition only. We are preparing fix now and will get back to you soon.

Thanks for reporting it!

**Comment by alexrandom** [comment]
@devishreebalasubramanian 

Issue was fixed and verified for Affirm 2 extension for Magento EE 2.1.0 and Magento CE 2.1.0.
Please, use latest extension version.
